build_from:
  aarch64: ghcr.io/hassio-addons/base:20.0.1
  amd64: ghcr.io/hassio-addons/base:20.0.1
  armv7: ghcr.io/hassio-addons/base:20.0.1
args:
  CHIRPSTACK_VERSION: 4.16.2
  CHIRPSTACK_GATEWAY_BRIDGE_VERSION: 4.1.1

#cosign:
#  identity: https://github.com/home-assistant/docker-base/.*
#labels:
#  io.hass.base.name: alpine
#  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
# https://github.com/hassio-addons/addon-base
