build_from:
  aarch64: ghcr.io/hassio-addons/base:18.1.1
  amd64: ghcr.io/hassio-addons/base:18.1.1
  armv7: ghcr.io/hassio-addons/base:18.1.1
args:
  CHIRPSTACK_VERSION: 4.14.1
  CHIRPSTACK_GATEWAY_BRIDGE_VERSION: 4.0.11

#cosign:
#  identity: https://github.com/home-assistant/docker-base/.*
#labels:
#  io.hass.base.name: alpine
#  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
# https://github.com/hassio-addons/addon-base
