# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Chirp2MQTT
version: "1.1.140"
slug: chirp2mqtt
description: HA add-on to incorporatex ChirpStack LoraWan devices into MQTT integration
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
url: "https://github.com/modrisb/chirpha"
startup: application
webui: http://[HOST]:[PORT:8080]
boot: auto
ports:
  8080/tcp: 8080
  1700/udp: 1700
ports_description:
  8080/tcp: "ChirpStack server WEB UI port"
  1700/udp: "Port to receive LoraWAN packets"
homeassistant: "2024.3.1"
map:
  - homeassistant_config
  - addon_config
  - addons
  - share:rw
init: false
options:
  application_id: ""
  mqtt_user: "loramqtt"
  mqtt_password: "ploramqtt"
  discovery_prefix: "homeassistant"
  options_start_delay: 2
  options_restore_age: 4
  options_online_per_device: 0
  options_add_expire_after: false
  options_log_level: "info"
  database_actions: "None"
  import_actions: "https://github.com/brocaar/lorawan-devices"
  lora_region: "eu868"
  chirpstack_secret: "you-must-replace-this"
schema:
  application_id: "str"
  mqtt_user: "str"
  mqtt_password: "str?"
  discovery_prefix: "str"
  options_start_delay: "int(1,)"
  options_restore_age: "int(1,)"
  options_online_per_device: "float(0,)"
  options_add_expire_after: "bool"
  options_log_level: "list(detail|debug|info|warning|error|fatal|critical)?"
  database_actions: "list(None|Backup|Restore|Backup and restore)?"
  import_actions: "str?"
  lora_region: "list(eu868|as923_2|as923_3|as923_4|as923|au915_0|au915_1|au915_2|au915_3|au915_4|au915_5|au915_6|au915_7|cn470_0|cn470_10|cn470_11|cn470_1|cn470_2|cn470_3|cn470_4|cn470_5|cn470_6|cn470_7|cn470_8|cn470_9|cn779|eu433|in865|ism2400|kr920|ru864|us915_0|us915_1|us915_2|us915_3|us915_4|us915_5|us915_6|us915_7)"
  chirpstack_secret: "str?"
timeout: 10
services:
  - mqtt:need
stage: experimental
